spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/book_social_network
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: localhost
    port: 1025
    username: eulu
    password: pass
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: yky8QxKh2cTERcKZHyCG56rprGfVxkBAhHu6D9eSdvSVWOhNF24LKMTzYw3p9ioo
      expiration: 86400000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account

server:
  port: 8088
